apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key-secret
type: Opaque
stringData:
  api-token: <path:apps-kv/data/cert-manager/config#cloudflare-api-token>
---
   apiVersion: cert-manager.io/v1
   kind: ClusterIssuer
   metadata:
     name: letsencrypt-prod
     namespace: cert-manager
   spec:
     acme:
       # The ACME server URL
       server: https://acme-v02.api.letsencrypt.org/directory
       #server: https://acme-staging-v02.api.letsencrypt.org/directory
       # Email address used for ACME registration
       email: <path:apps-kv/data/cert-manager/config#email_cert>
       # Name of a secret used to store the ACME account private key
       privateKeySecretRef:
         name: letsencrypt-prod
       # Enable the HTTP-01 challenge provider
       solvers:
       - dns01:
           cloudflare:
             email: <path:apps-kv/data/cert-manager/config#email_cloudflare>
             apiTokenSecretRef:
               name: cloudflare-api-key-secret
               key: api-token
