apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cert-manager-vault
  namespace: cert-manager
data:
  secretId: "<path:apps-kv/data/cert-manager/config#secretId_b64>"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault
  namespace: cert-manager
spec:
  vault:
    path:  pki-int/sign/home-dot-lan
    server: http://vault.vault:8200
    auth:
      appRole:
        path: approle
        roleId: "<path:apps-kv/data/cert-manager/config#roleId>"
        secretRef:
          name: cert-manager-vault
          key: secretId
