apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-internal
  namespace: cert-manager
spec:
  secretName: wildcard-internal-tls
  secretTemplate:
    labels:
      part-of: home.lan
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  commonName: home.lan
  dnsNames:
    - '*.home.lan'
    - 'home.lan'
  issuerRef:
    name: vault
    kind: ClusterIssuer
    group: cert-manager.io
