apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
spec:
  secretName: wildcard-tls
  secretTemplate:
    labels:
      part-of: <path:apps-kv/data/cert-manager/config#HOST2>
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  dnsNames:
    - '*.<path:apps-kv/data/cert-manager/config#HOST2>'
    - '<path:apps-kv/data/cert-manager/config#HOST2>'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
