apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-internal
spec:
  secretName: wildcard-internal-tls
  secretTemplate:
    labels:
      part-of: <path:apps-kv/data/cert-manager/config#HOST>
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  commonName: <path:apps-kv/data/cert-manager/config#HOST>
  dnsNames:
    - '*.<path:apps-kv/data/cert-manager/config#HOST>'
    - '<path:apps-kv/data/cert-manager/config#HOST>'
  issuerRef:
    name: vault
    kind: ClusterIssuer
    group: cert-manager.io
